RetailPOS.Web/Controllers/CategoriesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using RetailPOS.Web.Models;
using RetailPOS.Web.Services.IService;
using RetailPOS.Web.Utility;

namespace RetailPOS.Web.Controllers;


[Authorize(Roles = $"{UserRoleConstant.Admin},{UserRoleConstant.Manager}")]
public class CategoriesController : Controller
{
    
    private readonly ICategoryService _categoryService; 
    public CategoriesController(ICategoryService categoryService) =>  _categoryService = categoryService;
   
    #region GET: Categories
    public async Task<IActionResult> Index() => View(await _categoryService.GetCategoriesWithProductsAsync());
    #endregion


    #region GET: Categories/Create
    public IActionResult Create() => View();
    #endregion


    #region POST: Categories/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create([Bind("Name,Description")] Category category)
    {
        if (!ModelState.IsValid)
            return View(category);

        await _categoryService.CreateCategoryAsync(category);
        return RedirectToAction(nameof(Index));
    }
    #endregion


    #region GET: Categories/Edit/5
    public async Task<IActionResult> Edit(int id)
    {
        if (id is 0) return NotFound();
        var category = await _categoryService.GetCategoryByIdAsync(id);
        return category is null ? NotFound():  View(category);
    }
    #endregion


    #region POST: Categories/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Description")] Category category)
    {
        if (id != category.Id)
            return NotFound();

        if (!ModelState.IsValid)
            return View(category);

        var updated = await _categoryService.UpdateCategoryAsync(category);
        if (updated is null)
            return NotFound();

        return RedirectToAction(nameof(Index));
    }
    #endregion


    #region GET: Category/Details/5
    public async Task<IActionResult> Details(int id)
    {
        if (id is 0)
            return NotFound();

        var category = await _categoryService.GetCategoryWithProductsByIdAsync(id);

        return category is null ? NotFound() : View(category);
    }
    #endregion


    #region GET: Category/Delete/5
    public async Task<IActionResult> Delete(int id)
    {
        if (id is 0) return NotFound();

        var category = await _categoryService.GetCategoryWithProductsByIdAsync(id);

        return category is null ? NotFound() : View(category);

    }
    #endregion


    #region POST: Category/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var (success, error, category) = await _categoryService.DeleteConfirmAsync(id);

        if (success)
        {
            TempData["Success"] = "Category deleted successfully.";
            return RedirectToAction(nameof(Index));
        }

        if (error is "Category not found") return NotFound();

        if (category is not null)
        {
            ModelState.AddModelError("", error ?? "An error occurred while deleting.");
            return View("Delete", category);
        }

        TempData["Error"] = error ?? "Unexpected error.";
        return RedirectToAction(nameof(Index));
    }

    #endregion


}

RetailPOS.Web/Controllers/ClientController.cs
using Microsoft.AspNetCore.Mvc;
using RetailPOS.Web.Models.ViewModel;
using RetailPOS.Web.Services.IService;
using RetailPOS.Web.Utility;

namespace RetailPOS.Web.Controllers;

public class ClientController : Controller
{

    private readonly IProductService _productService;
    private readonly IRedisCacheService _redisCacheService;

    public ClientController(IProductService productService,
        IRedisCacheService redisCacheService)
    {
        _productService = productService;
        _redisCacheService = redisCacheService;
    }

    public async Task<IActionResult> Index()
    {
        if (User.Identity!.IsAuthenticated)
        {
            if (User.IsInRole(nameof(UserRoleConstant.Cashier))
                || User.IsInRole(nameof(UserRoleConstant.Manager)))
            {
                return RedirectToAction(nameof(Index), "Home");
            }
        }

        return View(await _productService.GetProductViewModelListsAsync());
    }

    public async Task<IActionResult> Cart()
    {
        var cartId = _redisCacheService.GetOrCreateCartId();
        var cart = await _redisCacheService.GetData<List<CartItemViewModel>>(cartId) ?? new();
        return View(cart);
    }

    [HttpPost]
    public async Task<IActionResult> AddToCart(int id)
    {
        var product = await _productService.GetProductViewModelWithIdAsync(id);
        if (product is null) return NotFound();

        var cartId = _redisCacheService.GetOrCreateCartId();

        var cart = await _redisCacheService.GetData<List<CartItemViewModel>>(cartId) ?? new();

        var item = cart.FirstOrDefault(c => c.ProductId == id);
        if (item is not null)
        {
            item.Quantity = 1;
        }
        else
        {
            cart.Add(new CartItemViewModel
            {
                ProductId = product.Id,
                ProductName = product.Name,
                Price = product.Price,
                Quantity = 1,
                imageUrl = product.ImageUrl
            });
        }

        await _redisCacheService.SetData(cartId, cart, TimeSpan.FromMinutes(30));
        return RedirectToAction(nameof(Cart));
    }

    [HttpPost]
    public async Task<IActionResult> UpdateCart(int ProductId, int Quantity)
    {


        var cartId = _redisCacheService.GetOrCreateCartId();
        var cart = await _redisCacheService.GetData<List<CartItemViewModel>>(cartId) ?? new();


        var item = cart.FirstOrDefault(c => c.ProductId == ProductId);
        if (item is not null)
        {
            if (Quantity <= 0)
                cart.Remove(item);
            else
                item.Quantity = Quantity;

            await _redisCacheService.SetData(cartId, cart, TimeSpan.FromMinutes(30));
        }

        return RedirectToAction(nameof(Cart));
    }


    [HttpPost]
    public async Task<IActionResult> RemoveCart(int ProductId)
    {
        var cartId = _redisCacheService.GetOrCreateCartId();
        var cart = await _redisCacheService.GetData<List<CartItemViewModel>>(cartId) ?? new();

        var item = cart.FirstOrDefault(c => c.ProductId == ProductId);
        if (item is not null)
            cart.Remove(item);


        await _redisCacheService.SetData(cartId, cart, TimeSpan.FromMinutes(30));


        return RedirectToAction(nameof(Index));
    }


    [HttpGet]
    public async Task<IActionResult> Checkout()
    {
        var cartId = _redisCacheService.GetOrCreateCartId();
        var cart = await _redisCacheService.GetData<List<CartItemViewModel>>(cartId) ?? new();

        var viewModel = new CheckoutViewModel
        {
            CartItems = cart
        };

        return View(viewModel);
    }


    [HttpPost]
    public IActionResult ProceedToCheckout() => RedirectToAction(nameof(Index), "Checkout");





}

RetailPOS.Web/Controllers/ProductsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using RetailPOS.Web.Services.IService;
using RetailPOS.Web.Models.ViewModel;
using RetailPOS.Web.Utility;

namespace RetailPOS.Web.Controllers;


[Authorize(Roles = $"{UserRoleConstant.Admin},{UserRoleConstant.Manager}")]
public class ProductsController : Controller
{
    private readonly IViewModelFactory _viewModelFactory;
    private readonly IProductService _productService;
    public ProductsController(
        IViewModelFactory viewModelFactory,
        IProductService productService)
    {
        _viewModelFactory = viewModelFactory;
        _productService = productService;
    }

    #region GET: Products
    public async Task<IActionResult> Index() => View(await _productService.GetProductViewModelListsAsync());
    #endregion


    #region GET: Products/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id is null) return NotFound();

        var product = await _productService.GetProductViewModelWithIdAsync(id);

        return product is null ? NotFound() : View( await _viewModelFactory.CreateProductViewModel(product));
    }
    #endregion


    #region GET: Products/Create
    public async Task<IActionResult> Create() => View(await _viewModelFactory.CreateProductViewModel());
    #endregion
    

    #region POST: Products/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ProductViewModel product, string? imageUrl, IFormFile? image)
    {
        if (!ModelState.IsValid) return View(await _viewModelFactory.CreateProductViewModel(product));

        product.ImageUrl = await _viewModelFactory.GetImageUrlAsync(imageUrl, image);

        var createdProduct = await _productService.CreateProductViewModelAsync(product);

        if (createdProduct is null)
        {
            ModelState.AddModelError("", "Failed to create product. Please try again.");
            return View(await _viewModelFactory.CreateProductViewModel(product));
        }

        return RedirectToAction(nameof(Index));
    }
    #endregion


    #region GET: Products/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id == null) return NotFound();

        var product = await _productService.GetProductViewModelWithIdAsync(id);

        return (product is null) ? NotFound() : View(await _viewModelFactory.CreateProductViewModel(product));
    }
    #endregion


    #region POST: Products/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, ProductViewModel product, string? imageUrl, IFormFile? image)
    {
        if (id != product.Id) return NotFound();

        if (!ModelState.IsValid)
            return View(await _viewModelFactory.CreateProductViewModel(product));


        product.ImageUrl = await _viewModelFactory.GetImageUrlAsync(imageUrl, image);


        var UpdatedProduct = await _productService.UpdateProductViewModelAsync(product); 


        if (UpdatedProduct is null)
        {
            TempData["Error"] = "Failed to update product.";
            return View(await _viewModelFactory.CreateProductViewModel(product));
        }
        
        return RedirectToAction(nameof(Index));

    }
    #endregion


    #region GET: Products/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id == null)
        {
            return NotFound();
        }

        var productViewModel = await _productService.GetProductViewModelWithIdAsync(id);

        if (productViewModel == null)
        {
            return NotFound();
        }

        return View(productViewModel);
    }
    #endregion


    #region POST: Products/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        bool deleted = await _productService.DeleteProductViewModelAsync(id);

        if (deleted)
            return RedirectToAction(nameof(Index));

        var product = await _productService.GetProductViewModelWithIdAsync(id);
        if (product == null) return NotFound();

        TempData["Error"] = "Unable to delete product, already have transaction.";
        return View(product);
    }
    #endregion



}

RetailPOS.Web/Controllers/SalesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using RetailPOS.Web.Data;
using RetailPOS.Web.Models;
using RetailPOS.Web.Utility;
using RetailPOS.Web.Services.IService;
using Mapster;
using RetailPOS.Web.Models.ViewModel;
using Microsoft.AspNetCore.Identity;
using System.Security.Claims;

namespace RetailPOS.Web.Controllers;

[Authorize(Roles = $"{UserRoleConstant.Admin},{UserRoleConstant.Manager}")]
public class SalesController : Controller
{

    private ISaleTransactionsService _saleTransactionsService;
    private IProductService _productService;
    private readonly UserManager<ApplicationUser> _userManager;
    public SalesController(
        IProductService productService,
        UserManager<ApplicationUser> userManager,
        ISaleTransactionsService saleTransactionsService)
    {

        _productService = productService;
        _userManager = userManager;
        _saleTransactionsService = saleTransactionsService;
    }

    #region GET: Sales
    public async Task<IActionResult> Index()
    {
        var sales = await _saleTransactionsService.GetTransactionsWithItemsAsync();

        var totalSales = sales.Sum(s => s.TotalAmount);
        var totalTransactions = sales.Count;
        var averageTransaction = totalTransactions > 0 ? totalSales / totalTransactions : 0;

        ViewBag.TotalSales = totalSales;
        ViewBag.TotalTransactions = totalTransactions;
        ViewBag.AverageTransaction = averageTransaction;
        return View(sales);
    }
    #endregion


    #region GET: Sales/Edit/5
    public async Task<IActionResult> Edit(int? id)
    {
        if (id is null) return NotFound();


        var sale = await _saleTransactionsService.GetTransactionWithItemsIdAsync(id.Value);


        if (sale is null) return NotFound();


        if (sale.Status is nameof(StatusEnum.COMPLETED)) return RedirectToAction(nameof(Index));


        ViewBag.Products = sale.Items
            .Where(i => i.Product != null)
            .Select(i => i.Product)
            .ToList()
            .OrderBy(i => i!.Name);

        return View(sale);
    }
    #endregion


    #region POST: Sales/Edit/5
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(int id, SalesTransaction sale)
    {
        if (id != sale.Id)
            return NotFound();

        if (!ModelState.IsValid)
            return View(sale);

        var updated = await _saleTransactionsService
            .UpdateTransactionStatusAsync(id, sale.Status, sale.PaymentStatus!);

        if (!updated)
            return RedirectToAction(nameof(Index));

        return RedirectToAction(nameof(Index));
    }
    #endregion


    #region GET: Sales/Details/5
    public async Task<IActionResult> Details(int? id)
    {
        if (id is null) return NotFound();

        var sale = await _saleTransactionsService
            .GetTransactionWithItemsIdAsync(id.Value);

        return sale is null ? NotFound() : View(sale);
    }
    #endregion


    #region GET: Sales/Create
    public async Task<IActionResult> Create()
    {
        var products = await _productService.GetCheckOutProductListAsync();

        ViewBag.Products = products.Adapt<List<ProductViewModel>>()
            .OrderBy(i => i.Name);

        return View();
    }
    #endregion


    #region POST: Sales/Create
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(SalesTransaction sale)
    {
        if (!ModelState.IsValid)
        {
            var products = await _productService.GetCheckOutProductListAsync();

            ViewBag.Products = products.Adapt<List<ProductViewModel>>()
                .OrderBy(i => i.Name);

            return View(sale);
        }



        var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
        var user = await _userManager.FindByIdAsync(userId!);
        if (user == null) return Unauthorized();

        // Set user info into the incoming model
        sale.UserId = userId;
        sale.CustomerName = $"{user.FirstName} {user.LastName}";
        sale.CustomerEmail = user.Email;
        sale.TransactionDate = DateTime.UtcNow;
        sale.Status = nameof(StatusEnum.PENDING);
        sale.PaymentMethod = "SALE_CREATE";
        sale.PaymentStatus = nameof(StatusEnum.PENDING);

        await _saleTransactionsService.CreateNewSaleTransaction(sale);

        return RedirectToAction(nameof(Index));
    }
    #endregion


    #region GET: Sales/Delete/5
    public async Task<IActionResult> Delete(int? id)
    {
        if (id is null)
            return NotFound();

        var result = await _saleTransactionsService.GetTransactionsWithByIdAsync(id.Value);

        if (result is null)
            return NotFound();

        if (result.Status is nameof(StatusEnum.COMPLETED))
        {
            TempData["Error"] = "Completed transactions cannot be deleted.";
            return RedirectToAction(nameof(Index));
        }

        return View(result);
    }
    #endregion


    #region POST: Sales/Delete/5
    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        var success = await _saleTransactionsService.DeleteSaleTransactionAsync(id);

        if (!success)
        {
            TempData["Error"] = "Unable to delete transaction. It may not exist or is already completed.";
            return RedirectToAction(nameof(Index));
        }

        TempData["Success"] = "Sale transaction deleted successfully.";
        return RedirectToAction(nameof(Index));
    }
    #endregion


    #region GET: Sales/Report
    public async Task<IActionResult> Report(DateTime? startDate, DateTime? endDate) =>
        View(await _saleTransactionsService.GetSalesTransactionsReportAsync(startDate, endDate));
    #endregion
}

RetailPOS.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MaD POS</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.7.2/font/bootstrap-icons.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark  border-bottom box-shadow mb-3">
            <div class="container">
                @{
                    var isAuth = User.Identity?.IsAuthenticated ?? false;
                }

                @if (isAuth)
                {
                    <a class="navbar-brand text-xxl-start text-muted" asp-area="" asp-controller="Home" asp-action="Index">MaD POS</a>
                }
                else
                {
                    <a class="navbar-brand text-xxl-start text-muted" asp-area="" asp-controller="Client" asp-action="Index">MaD Shop</a>
                }

                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav">
                        @if (isAuth)
                        {
                            if (User.IsInRole("Admin") || User.IsInRole("Manager"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                                </li>

                                if (User.IsInRole("Admin"))
                                {
                                    <li class="nav-item">
                                        <a class="nav-link text-white" asp-controller="Client" asp-action="Index">Shop</a>
                                    </li>

                                }

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Products" asp-action="Index">Products</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Categories" asp-action="Index">Categories</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Sales" asp-action="Report">Reports</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Sales" asp-action="Index">Sales</a>
                                </li>
                            }

                            if (User.IsInRole("Cashier"))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="CheckOut" asp-action="Index"> CheckOut </a>
                                </li>
                            }
                        }
                    </ul>

                    <ul class="navbar-nav">
                        @if (isAuth)
                        {
                            //<li class="nav-item border border-light rounded-pill px-3 ps-3">
                            //  <span class="nav-link text-muted">Hello, <span class="text-info">@User.Identity?.Name</span></span>
                            //</li>

                            @if (User.IsInRole("Admin"))
                            {

                                <li class="nav-item">
                                    <a class="nav-link text-white" asp-controller="Client" asp-action="Cart">
                                        <i class="bi bi-cart"></i>
                                    </a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-warning px-3" asp-controller="Account" asp-action="Register">Register</a>
                                </li>
                            }

                            <li class="nav-item">
                                <form asp-controller="Account" asp-action="Logout" method="post" class="d-inline">
                                    <button type="submit" class="nav-link btn btn-link text-warning">Logout</button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Client" asp-action="Cart">
                                    <i class="bi bi-cart"></i>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-warning px-3" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3" style="color: #efecec;">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-muted border text-center text-xl-start">
            &copy; 2025 - MaD POS
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"> </script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await Html.PartialAsync("_Notifications")
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

RetailPOS.Web/Views/Shared/_Notifications.cshtml
<script>
    toastr.options = {
        closeButton: true,
        progressBar: true,
        positionClass: "toast-top-center",
        timeOut: "5000"
    };

    @if (TempData["Success"] != null)
    {
        <text>toastr.success('@TempData["Success"]'); </text>
    }

    @if (TempData["Error"] != null)
    {
        <text>toastr.error('@TempData["Error"]'); </text>
    }
</script>